baseURL = "/website"
languageCode = "en-us"
title = "Arrai"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30


[params]
  google_analytics_id=""
  homepage_button_link = 'https://github.com/arr-ai/arrai'
  homepage_button_text = 'See on Github'
  homepage_intro = 'The ultimate data engine.'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "The ultimate data engine."
    meta_og_title = "Arrai"
    meta_og_type = "website"
    meta_og_url = "/website"
    meta_og_description = "The ultimate data engine."
    meta_twitter_card = "summary"

  [params.logo]
      standard = "arrai-logo.png"

